CREATE TABLE Room (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name TEXT NOT NULL,
capacity INTEGER NOT NULL);

CREATE TABLE Exams (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name INTEGER NOT NULL,
roomId INTEGER NOT NULL,
start DATE NOT NULL,
duration INTEGER NOT NULL,
attendees INTEGER NOT NULL,
FOREIGN KEY(roomId) REFERENCES Room(id));

CREATE TABLE OperatingTime (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
day DATE NOT NULL,
room INTEGER NOT NULL,
daySchedule INTEGER NOT NULL,
FOREIGN KEY(room) REFERENCES Room(id),
FOREIGN KEY(daySchedule) REFERENCES DaySchedule(id));

CREATE TABLE TimeSlots (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
Start DATE NOT NULL,
Duration INTEGER NOT NULL,
daySchedule INTEGER NOT NULL,
FOREIGN KEY(daySchedule) REFERENCES DaySchedule(id));

CREATE TABLE DaySchedule (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name TEXT NOT NULL);

CREATE TABLE Teacher (
id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
name TEXT NOT NULL,
eMail TEXT NOT NULL);

CREATE TABLE assist (
examId INTEGER NOT NULL,
teacherId INTEGER NOT NULL,
mode TEXT NOT NULL,
FOREIGN KEY(examId) REFERENCES Exams(id),
FOREIGN KEY(teacherId) REFERENCES Teacher(id));

